"""Adicionar campos completos Provedor v3

Revision ID: e86281ee7893
Revises: 978afcf3303f
Create Date: 2025-11-18 12:42:23.708595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86281ee7893'
down_revision = '978afcf3303f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_provedores')
    with op.batch_alter_table('provedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razao_social', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('nome_fantasia', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contato_principal', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_provedor_cnpj', ['cnpj'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provedores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_provedor_cnpj', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('active')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('endereco')
        batch_op.drop_column('cep')
        batch_op.drop_column('contato_principal')
        batch_op.drop_column('website')
        batch_op.drop_column('email')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('telefone')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('nome_fantasia')
        batch_op.drop_column('razao_social')

    op.create_table('_alembic_tmp_provedores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('razao_social', sa.VARCHAR(length=200), nullable=True),
    sa.Column('nome_fantasia', sa.VARCHAR(length=200), nullable=True),
    sa.Column('cnpj', sa.VARCHAR(length=18), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('contato_principal', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cep', sa.VARCHAR(length=9), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=True),
    sa.Column('numero', sa.VARCHAR(length=10), nullable=True),
    sa.Column('complemento', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=100), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=2), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj', name=op.f('uq_provedor_cnpj'))
    )
    # ### end Alembic commands ###
